//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRmonitorsSetup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XRmonitorsSetup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HP Windows Mixed Reality Headset]
        ///K1=-0.7
        ///Scale=14.0
        ///OffsetX=0.247
        ///OffsetY=-0.208
        ///EyeCantX=-0.623
        ///EyeCantY=-0.264
        ///EyeCantZ=0.0
        ///
        ///[DELL VISOR VR118]
        ///K1=-0.7
        ///Scale=14.0
        ///OffsetX=0.247
        ///OffsetY=-0.208
        ///EyeCantX=-0.623
        ///EyeCantY=-0.264
        ///EyeCantZ=0.0
        ///
        ///[Lenovo Explorer]
        ///K1=-0.7
        ///Scale=14.0
        ///OffsetX=0.227
        ///OffsetY=-0.240
        ///EyeCantX=-0.554
        ///EyeCantY=-0.337
        ///EyeCantZ=0.0
        ///
        ///[Samsung Windows Mixed Reality]
        ///K1=-0.7
        ///Scale=18.0
        ///OffsetX=0.231
        ///OffsetY=-0.116
        ///EyeCantX=-0.472
        ///EyeCantY=-0.326
        ///EyeCantZ=0.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string camera_calibration {
            get {
                return ResourceManager.GetString("camera_calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iDLL64 {
            get {
                object obj = ResourceManager.GetObject("iDLL64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ToggleSwitch {
            get {
                object obj = ResourceManager.GetObject("ToggleSwitch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XRmonitorsCamera {
            get {
                object obj = ResourceManager.GetObject("XRmonitorsCamera", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XRmonitorsHologram {
            get {
                object obj = ResourceManager.GetObject("XRmonitorsHologram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XRmonitorsInstaller {
            get {
                object obj = ResourceManager.GetObject("XRmonitorsInstaller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XRmonitorsService {
            get {
                object obj = ResourceManager.GetObject("XRmonitorsService", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XRmonitorsUI {
            get {
                object obj = ResourceManager.GetObject("XRmonitorsUI", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
